[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_VNC_SCREEN)s +extension RANDR
user=chrome
autorestart=true
priority=100

[program:fluxbox]
environment=HOME="/home/chrome",DISPLAY=":1",USER="chrome"
command=/usr/bin/fluxbox
user=chrome
autorestart=true
priority=150

[program:vlc]
environment=HOME="/home/chrome",DISPLAY=":1",USER="chrome"
command=/bin/bash /start-vlc.sh
user=chrome
autorestart=true
priority=200

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 %(ENV_X11VNC_AUTH)s %(ENV_X11VNC_OPTS)s
user=chrome
autorestart=true
priority=300

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ 6080 127.0.0.1:5900
user=chrome
autorestart=true
priority=350

[program:audio-proxy]
environment=HOME="/home/chrome",USER="chrome"
command=/bin/bash /start-audio-proxy.sh
user=chrome
autorestart=true
priority=400
